services:
  postgres:
    image: postgres:13
    container_name: testdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6
    container_name: library-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
