spring:
  application:
    name: book-service

  config:
    activate:
      on-profile: "!test"
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      label: task12
